# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = "benhosmer/ossim-geotools"
  config.vm.box = "ossim-testing"

  #config.vm.network "private_network", ip: "192.168.33.202", auto_config: false

  config.vm.synced_folder "../", "/ossim-geotools"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end
  #
end
